### ISSUE TITLE
use "deprovision" operation to remove log drains

### ISSUE THREAD

**Issue by bantic** [aptible/diesel.aptible.com#101]
After discussion with @fancyremarker we shouldn't `DELETE /log_drains/:log_drain_id` from diesel directly. Better to use a deprovision operation like we do when deprovisioning apps and dbs. The UI may need to change to avoid displaying deprovisioned log drains (treating them as though they are deleted).

refs #98

**Comment by bantic** [comment]
@fancyremarker Is it still ok to `POST /log_drains` from diesel to create a new log drain?

**Comment by aaw** [comment]
Out of curiosity, what's the rationale for a separate deprovision job versus allowing Diesel to update the state of the log drains and then just run a configure log drain job?

**Comment by bantic** [comment]
I'm not sure. Are you saying diesel would change status of the log drain to "deprovisioned" and at the same time create an operation for that log drain of type "configure"? I'm not sure what the configure job does but that may achieve the same effect as a separate deprovision job. I guess there may be potential problems having it be a two-phase process (change log drain status, then create deprovision op) from the client-side because only one of the two may succeed, leaving the log drain in a dangling state?

**Comment by fancyremarker** [comment]
@aaw: I think a `deprovision` job is appropriate for the use case of removing a drain entirely. (For example, a user provisions a Papertrail drain, then adds an Elasticsearch drain, then wishes to remove the Papertrail drain.)

Does that sound right to you?

**Comment by aaw** [comment]
Sorry, not trying to start a centithread - I'm just interested in understanding why Diesel shouldn't `DELETE /log_drains/:log_drain_id`, since that probably means that I'm approaching this the wrong way from Sweetness.

Some more background: on the Sweetness side, log drains are implemented with one logstash instance per account. Several forwarders send logs to the account's logstash instance and that instance forwards the logs to their final destination (syslog, elasticsearch, etc.) Any change of log drains needs to be followed by a "re-configure" of logging on the Sweetness side, which means a new logstash config is generated from the current state of all log drains and logstash is restarted. Right now, we have a ConfigureLogDrain job in sweetness that does just that. So whether you add a log drain, delete a log drain, or modify a log drain, it has to be followed by a ConfigureLogDrain in Sweetness to take effect.

The way I'm reading this issue is that we want to add a new DeprovisionLogDrain operation instead of a DELETE of the log drain followed by a ConfigureLogDrain. Is that correct? In that case, wouldn't we also need a ProvisionLogDrain operation? In both cases, under the hood Sweetness would just make a modification to the API and run ConfigureLogDrain anyway, so I'm wondering why explicit Provision/Deprovision operations are preferred to allowing diesel to do whatever CRUD operations it wants and run a configure.

**Comment by bantic** [comment]
After discussion w/ @fancyremarker and mentioned in #129 we'll hold off on allowing users to remove log drains through diesel for now.
