### ISSUE TITLE
App navigation tabs are wonky

### ISSUE THREAD

**Issue by sandersonet** [aptible/diesel.aptible.com#168]
On production, I am still seeing an issue with multiple tabs being 'active' or the incorrect tab being 'active'.  To reproduce, just visit an app: https://diesel.aptible.com/apps/367 and toggle between Domains and Activity.  

Two active tabs (I'm not hovering): 
![screenshot 2015-03-18 09 50 21](https://cloud.githubusercontent.com/assets/884151/6710090/b02e817e-cd54-11e4-9a0b-582d4c13b2a1.png)

Incorrect active tab:
![screenshot 2015-03-18 09 50 50](https://cloud.githubusercontent.com/assets/884151/6710099/bcda8f26-cd54-11e4-9723-9c14413d8084.png)

DOM shows incorrect tab still has active class:
![screenshot 2015-03-18 09 52 23](https://cloud.githubusercontent.com/assets/884151/6710101/cac14ad0-cd54-11e4-9356-ff9183052caa.png)

**Comment by mixonic** [comment]
@sandersonet I believe this is due to:

https://github.com/aptible/api.aptible.com/pull/182

The exception from the unhandled failure leave the runloop in a broken state.

This request (images) should probably not be made anyway, as the data is already sideloaded. Regardless I'd like to see the CORs fix go to staging and test this there first.

**Comment by sandersonet** [comment]
Confirmed, fixed by  aptible/api.aptible.com#182

**Comment by mixonic** [comment]
I'm still seeing this on staging, where I've deployed the latest revs of everything (and no longer see that CORs error).

**Comment by sandersonet** [comment]
You're right.  the CORS error was causing the incorrect tab to be active, but something else is causing both tabs to be active.
