### ISSUE TITLE
Organization > Delete Role

### ISSUE THREAD

**Issue by mixonic** [aptible/diesel.aptible.com#206]

**Comment by sandersonet** [comment]
@mixonic There are some important caveats about users and roles that I'd like to point out:

1) We don't ever want to allow an organization to exist without at least 1 privileged **user** present
2) When deleting a role, it's possible you are removing users from the organization.  If any of the role members only belong to one role(this role), then we should prevent that role from being deleted and alert the user "You cannot delete this role as it is @mixonic 's and @sandersonet 's only role in the Aptible organization"
3) When editing a user's set of roles you shouldn't be able to uncheck all of their roles:  [example](https://www.dropbox.com/s/sxk2br8ngsnp70m/Screenshot%202015-03-24%2011.55.06.png?dl=0)
Again, if you uncheck all of their roles, you'll effectively remove them from the organization and have to re-invite them.  

The current dashboard does a good job enforcing these rules, but since they are edge cases that are hard to spot, I wanted to be sure to point them out before you started working on this.

**Comment by mixonic** [comment]
@sandersonet thanks, very useful
